# Generated by Django 5.1.7 on 2025-04-04 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_task_link_alter_task_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='link',
            field=models.CharField(default='', max_length=200),
        ),
    ]
