# Generated by Django 5.1.7 on 2025-04-04 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_task_description_alter_task_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='estimated_time',
            new_name='estimated_time_mins',
        ),
        migrations.AlterField(
            model_name='task',
            name='link',
            field=models.URLField(default='', max_length=500),
        ),
    ]
