# Generated by Django 5.1.7 on 2025-04-04 20:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_rename_estimated_time_task_estimated_time_mins_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 4, 4, 20, 19, 17, 600328, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
