# Generated by Django 5.1.7 on 2025-04-05 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_userprofile_date_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='total_reward',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='total_task_completed',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
