# Generated by Django 5.1.7 on 2025-04-05 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_userprofile_total_reward_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='streak',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
