# Generated by Django 5.1.7 on 2025-04-06 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_userprofile_streak'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('social_media', 'social_media'), ('videos', 'videos'), ('surveys', 'survey'), ('others', 'others')], default='others', max_length=100),
        ),
        migrations.AlterField(
            model_name='usertask',
            name='proof',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
