# Generated by Django 5.1.7 on 2025-04-06 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_task_category_alter_usertask_proof'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usertask',
            old_name='proof',
            new_name='proof_image',
        ),
        migrations.AddField(
            model_name='usertask',
            name='proof_username',
            field=models.CharField(default='user.firstname', max_length=200),
        ),
    ]
