# Generated by Django 5.1.7 on 2025-04-07 10:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_useraccountdetails'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserAccountDetails',
            new_name='UserAccountDetail',
        ),
    ]
