# Generated by Django 5.1.7 on 2025-04-07 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_rename_useraccountdetails_useraccountdetail'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='useraccountdetail',
            unique_together=set(),
        ),
    ]
