# Generated by Django 5.1.7 on 2025-04-07 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_useraccountdetail_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccountdetail',
            name='account_number',
            field=models.IntegerField(default=''),
        ),
    ]
