# Generated by Django 5.1.7 on 2025-04-07 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_alter_useraccountdetail_account_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccountdetail',
            name='account_number',
            field=models.CharField(max_length=10),
        ),
    ]
