# Generated by Django 5.1.7 on 2025-04-07 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_alter_useraccountdetail_account_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='task_earning',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
