# Generated by Django 5.1.7 on 2025-04-10 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_alter_usertask_proof_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='amount_tasker',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
