# Generated by Django 5.1.7 on 2025-04-12 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_task_amount_tasker'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='locked_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
