# Generated by Django 5.1.7 on 2025-04-26 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_deposit'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='num_of_completed',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
