# Generated by Django 5.1.7 on 2025-04-26 15:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_task_num_of_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 4, 26, 15, 51, 7, 592095, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
