# Generated by Django 5.1.7 on 2025-05-09 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_top_up'),
    ]

    operations = [
        migrations.AlterField(
            model_name='top_up',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
